version: '2'
services:
    aaaaaaaaaaaa-app:
        image: aaaaaaaaaaaa
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://aaaaaaaaaaaa-mssql:1433;database=aaaaaaaaaaaa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aaaaaaaaaaaa-mssql:
        extends:
            file: mssql.yml
            service: aaaaaaaaaaaa-mssql
